# 数据源配置
spring:
  rabbitmq:
    host: 192.168.43.129
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          #最大重试次数
          max-attempts: 5
          #最大重试时间间隔
          max-interval: 10000
          #投递消息的间隔时间ms
          initial-interval: 2000
          #距离上次重试间隔乘数因子
          multiplier: 2
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/dbtoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        dbedge:
          url: jdbc:mysql://localhost:3306/dbedge?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: itsskytss
  # 令牌有效期（默认30分钟）
  expireTime: 30

itssky-sso-base-ip: http://192.168.200.193
itssky-sso-base-port: 8080
itssky:
  sso:
    client:
      enabled: true
      #即本服务部署的ip地址，要求前端也跟后端在同一台服务器上，不然就要配置前端ip
      base-ip: http://192.168.200.193
      base-front-port: 80
      base-back-port: 8089
    schedule:
      enabled: true
      remote-sso-url: ${itssky-sso-base-ip}:${itssky-sso-base-port}
      remote-sso-ping-url: ${itssky-sso-base-ip}:${itssky-sso-base-port}/check/status
      corp-no:


secure:
  ignored:
    urls: #安全路径白名单
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /api/auth/login
      - /admin/logout
      - /api/websocket/**
      - /api/bigscreen/index/subDeviceStatus/**
      - /api/device/upload/**
      - /captchaImage
      - /sso/client/token/handle