# 数据源配置
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/dbtoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        dbedge:
          url: jdbc:mysql://localhost:3306/dbedge?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        dbtoms:
          url: jdbc:mysql://localhost:3306/dbtoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        dbstats:
          url: jdbc:mysql://localhost:3306/dbstats?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: itsskytss
  # 令牌有效期（默认30分钟）
  expireTime: 30

#current-service-ip: 172.20.10.3
current-service-ip: 192.168.200.127
#current-service-ip: 192.168.50.66
#current-service-ip: 172.20.10.4
itssky:
  sso:
    # 本应用服务相关配置
    client:
      #是否启用单点
      enabled: true
      #即本服务部署的ip地址，要求前端也跟后端在同一台服务器上，不然就要配置前端ip[初版默认同一台服务器，后期增加前端配置]
      base-ip: http://${current-service-ip}
      # 前端端口，nginx代理端口
      base-front-port: 80
      # 后端端口
      base-back-port: ${server.port}
      corp-no:
      cache-key-prefix: login_tokens_stat
    # 单点登陆服务端ip+port
    server:
      base-ip: 172.20.10.10
      base-port: 8080
    # 下列不需要配置修改
    schedule:
      enabled: ${itssky.sso.client.enabled}
      remote-sso-url: http://${itssky.sso.server.base-ip}:${itssky.sso.server.base-port}
      remote-sso-ping-url: http://${itssky.sso.server.base-ip}:${itssky.sso.server.base-port}/check/status

secure:
  ignored:
    urls: #安全路径白名单
      - /captchaImage
      - /
      - /*.html
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /profile/**
      - /sso/client/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /*/api-docs
      - /druid/**
      - /common/**
      - /logout

