# 数据源配置
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: dbtoms
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
      datasource:
        dbtoms:
          url: jdbc:mysql://172.51.0.100:3306/dbtoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: RU#@xcN1NGSp
          driver-class-name: com.mysql.jdbc.Driver
        dbedge:
          url: jdbc:mysql://172.51.0.100:3306/dbedge?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: RU#@xcN1NGSp
          driver-class-name: com.mysql.jdbc.Driver
        dbaudit:
          url: jdbc:mysql://172.51.0.100:3306/dbaudit?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: RU#@xcN1NGSp
          driver-class-name: com.mysql.jdbc.Driver
        dbstats:
          url: jdbc:mysql://172.51.0.100:3306/dbstats?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: RU#@xcN1NGSp
          driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 2
    # 密码
    password: itssoft
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: itsskytss
  # 令牌有效期（默认30分钟）
  expireTime: 720

current-service-ip: 172.51.0.100
#current-service-ip: 10.15.0.99
itssky:
  sso:
    client:
      enabled: true
      #即本服务部署的ip地址，要求前端也跟后端在同一台服务器上，不然就要配置前端ip
      base-ip: http://${current-service-ip}
      base-front-ip: http://139.198.181.105
      base-front-port: 19093
      base-back-port: ${server.port}
      corp-no:
      cache-key-prefix: login_tokens_stat
    server:
      base-ip: 172.51.0.100
      base-port: 8091
      base-front-ip: 139.198.181.105
      base-front-port: 19091
    schedule:
      enabled: ${itssky.sso.client.enabled}
      remote-sso-url: http://${itssky.sso.server.base-ip}:${itssky.sso.server.base-port}
      remote-sso-ping-url: http://${itssky.sso.server.base-ip}:${itssky.sso.server.base-port}/check/status
      remote-sso-redirect-url: http://${itssky.sso.server.base-front-ip}:${itssky.sso.server.base-front-port}

secure:
  ignored:
    urls: #安全路径白名单
      - /captchaImage
      - /
      - /*.html
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /profile/**
      - /sso/client/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /*/api-docs
      - /logout